name: AWS CT

on:
  push:
    paths:
      - 'control_tower/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'control_tower/**'

env:
  TF_LOG: INFO
  AWS_REGION: ap-southeast-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        run: |
          cd control_tower
          terraform init

      - name: Terraform Plan
        run: |
          cd control_tower
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd control_tower
          terraform apply -auto-approve -input=false
